version: "3.9"

services:
  db:
    image: postgres:15
    container_name: tricount-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tricount
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/app/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: tricount-backend
    depends_on:
      - db
    environment:
      DATABASE_USER: postgres
      DATABASE_PW: postgres
      DATABASE_NAME: tricount
      JWT_SECRET_KEY: supersecret
      JWT_ALGORITHM: HS256
      JWT_EXPIRATION_MINUTES: 30
      LOG_FORMAT: "%(levelname)s | %(message)s"
      BASE_LOGGER_NAME: tricount
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: tricount-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    # volumes:
    #   - ./frontend:/app
    # command: npm start

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: tricount-prometheus
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana:11.1.0
    container_name: tricount-grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/dashboards/json:/var/lib/grafana/dashboards

volumes:
  postgres_data:
  prom_data:
  grafana_data:
